# Generated by Django 3.0.7 on 2021-04-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('dono', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('conteudo', models.CharField(blank=True, choices=[('Cenouras', 'Cenouras'), ('Batatas', 'Batatas'), ('Feijões', 'Feijões'), ('Alho Francês', 'Alho Francês'), ('Couve Portuguesa', 'Couve Portuguesa'), ('Bróculos', 'Bróculos'), ('Alface', 'Alface'), ('Tomate', 'Tomate')], max_length=64, null=True)),
                ('status', models.CharField(max_length=100)),
                ('relatorio', models.TextField()),
                ('imagem1', models.ImageField(blank=True, upload_to='reports/')),
                ('imagem2', models.ImageField(blank=True, upload_to='reports/')),
                ('imagem3', models.ImageField(blank=True, upload_to='reports/')),
                ('imagem4', models.ImageField(blank=True, upload_to='reports/')),
                ('imagem5', models.ImageField(blank=True, upload_to='reports/')),
                ('imagem6', models.ImageField(blank=True, upload_to='reports/')),
                ('envio', models.CharField(blank=True, choices=[('Não-Enviado', 'Nã-Enviado'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido')], max_length=64, null=True)),
            ],
        ),
    ]
